name: Release

on: push

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Generate binaries for macOS, Linux and Windows
        run: npm run package
      - name: Rename macOS binary to conform to GitHub CLI extension rules
        run: mv bin/migration-audit-macos bin/gh-migration-audit-darwin-amd64
      - name: Rename Windows binary to conform to GitHub CLI extension rules
        run: mv bin/migration-audit-win.exe bin/gh-migration-audit-windows-amd64.exe
      - name: Rename Linux binary to conform to GitHub CLI extension rules
        run: mv bin/migration-audit-linux bin/gh-migration-audit-linux-amd64
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/gh-migration-audit-darwin-amd64
            bin/gh-migration-audit-linux-amd64
            bin/gh-migration-audit-windows-amd64.exe
          generate_release_notes: true
